#!/bin/sh
# Commit twice every day.
set -e

USAGE="$0 [directory]"

REPOSITORY="$1"
if ! test -d "$REPOSITORY"; then
  echo "$USAGE" > /dev/stderr
  exit 1
fi

HALFDAY=$((60 * 60 * 12))
END=$(($(date +%s) + 100 * $HALFDAY))


cd "$REPOSITORY"

if test -f date; then
  now=$(cat date)
else
  now=$(date -d 2005-08-03 +%s)
  git init
  touch date
fi
git add date
while test $now -lt $END; do
  now=$(($now + $HALFDAY))
  random=$(($HALFDAY * $RANDOM / 32767))
  commit=$(($now + $random))
  echo $commit > date
  export GIT_AUTHOR_DATE=$commit 
  export GIT_COMMITTER_DATE=$commit 
  git commit date -m $commit > /dev/null
done
