#!/bin/sh
# Commit twice every day.
set -e

HALFDAY=$((60 * 60 * 12))
END=$(date +%s)

now=$(date -d 2005-08-03 +%s)
while test $now -lt $END; do
  now=$(($now + $HALFDAY))
  random=$(($HALFDAY * $RANDOM / 32767))
  echo $random
done

# GIT_AUTHOR_DATE and GIT_COMMITTER_DATE 
